name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose a Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Deploy to Production
        run: |
          # Add commands to deploy your built Vite app to your hosting platform here
          # Examples: deploying to Vercel, Netlify, or custom hosting servers

